### PR TITLE
Change System Clock to 72MHz

### PR DESCRIPTION
**Pull request by tusker-tools**
**main.c**
- Change System Clock to 72Mhz in order to improve compatibility to the main application (implements #11 )

**.ioc**
- Update to CubeMX 6
- Change clock configuration to 72MHz external oscillator
- Remove MX_USB_DEVICE_Init function call generation, as we placed it in the user code section in main file and thus, CubeMX would generate additional function call which leads to failed build

**overall**
- Update some files to new firmware package version (driver files not updated as code size increases with them)

### CODE REVIEW

**Comment by Goutamvg** [comment]
hi sir 
can i get bootloader's application project files sir .. please .....

**Comment by tusker-tools** [comment]
> hi sir can i get bootloader's application project files sir .. please .....

You can find (and download) all the project files in my github branch

**Comment by Goutamvg** [comment]
> > hi sir can i get bootloader's application project files sir .. please .....
> 
> You can find (and download) all the project files in my github branch

thank you sir.  But the bootloader applications project files are not uploaded only hex files are there . please share the project files it would be more helpful.. 
thank you

**Comment by tusker-tools** [comment]
Now I got it... I suppose you meant the files for using the projects with CubeIDE, right?
I uploaded the files for compiling the project with CubeIDE. Hope that it's working for you now.

**Comment by Goutamvg** [comment]
Thank you sir. The only thing i was asking that how did you created the example hex file. If you have the example hex files project using cubeIDE or MDK-ARM please share it. It would be great for my study. 
Screenshot 2022-09-15 110401

**Comment by tusker-tools** [comment]
I did not create the example application, therefore I can't provide you the project files.

But there is nothing special about it. You can use any blinky application you find in github. To make it work with the bootloader, you simply need to change two things:
1. Define interrupt vector table offset according to the start address of your main application:
`#define VECT_TAB_OFFSET         0x00004000U`
3. Change the linker skript to match your main application start:
 `FLASH (rx)    	: ORIGIN = 0x8004000,   	LENGTH = 48K`

Of course, the main application start address must match the jump address in the bootloader

**Comment by Goutamvg** [comment]
> I did not create the example application, therefore I can't provide you the project files.
> 
> But there is nothing special about it. You can use any blinky application you find in github. To make it work with the bootloader, you simply need to change two things:
> 
> 1. Define interrupt vector table offset according to the start address of your main application:
>    `#define VECT_TAB_OFFSET         0x00004000U`
> 2. Change the linker skript to match your main application start:
>    `FLASH (rx)    	: ORIGIN = 0x8004000,   	LENGTH = 48K`
> 
> Of course, the main application start address must match the jump address in the bootloader

thankyou so much sir ....

**Comment by tusker-tools** [comment]
@sfyip, could you pls. merge my pull request?
In the meanwhile I have fixed two severe issues which have a big probability to affect the main application.

1. If you use 72MHz clock in the main application, the usual clock initialization procedure is not able to change the 48MHz config set by bootloader
2. If e.g. FreeRTOS is used, the SysTick counter keeps running when jumping to the main application. This triggers a SysTick interrupt before FreeRTOS setup is finished, causing a HardFault

To find those, I spent at least 2 days of debugging ;-)

**Comment by canmot** [comment]
> I did not create the example application, therefore I can't provide you the project files.
> 
> But there is nothing special about it. You can use any blinky application you find in github. To make it work with the bootloader, you simply need to change two things:
> 
> 1. Define interrupt vector table offset according to the start address of your main application:
>    `#define VECT_TAB_OFFSET         0x00004000U`
> 2. Change the linker skript to match your main application start:
>    `FLASH (rx)    	: ORIGIN = 0x8004000,   	LENGTH = 48K`
> 
> Of course, the main application start address must match the jump address in the bootloader

I`ve done these steps for many times, but i can`t launch my hex via this bootloader. Please help me

**Comment by canmot** [comment]
Done...if you need to make your own main project, need to do it from bootloader program whith similar clock options. And you need #define VECT_TAB_OFFSET         0x00004000U . Also need to modify .scr file

 LR_IROM1 0x08004000 0x000C000  {    ; load region size_region
  ER_IROM1 0x08004000 0x000C000  {  ; load address = execution address

**Pull request merged**
